import React, { useEffect } from "react";
import { useParams } from "react-router-dom";
import { Box } from "@mui/material";
import Logotop from "../component/layout/LogoTop";
import Navbardesktop from "../component/layout/NavBarDesktop";
import FooterDesktop from "../component/layout/FooterDesktop";
import { styles } from "../styles";

const policiesContent = [
  `<p class="MsoNormal" style="text-align: center; line-height: 150%;" align="center"><strong><span style="font-size: 16.0pt; line-height: 150%; font-family: 'Inter',serif;">CH&Iacute;NH S&Aacute;CH AN TO&Agrave;N V&Agrave; SỨC KHỎE</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">The Thanh Coffee sẽ t&iacute;ch cực th&uacute;c đẩy c&aacute;c hoạt động an to&agrave;n v&agrave; sức khỏe với sự tham gia của tất cả nh&acirc;n sự dựa tr&ecirc;n việc đảm bảo an to&agrave;n v&agrave; sức khỏe của tất cả nh&acirc;n vi&ecirc;n l&agrave;m nền tảng quản l&yacute;.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để thực hiện ch&iacute;nh s&aacute;ch sức khỏe v&agrave; an to&agrave;n của n&agrave;y, ch&uacute;ng t&ocirc;i sẽ l&agrave;m việc tr&ecirc;n ba mục sau dựa tr&ecirc;n Sứ mệnh, Lời hứa v&agrave; Gi&aacute; trị của ch&uacute;ng t&ocirc;i.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Hỗ trợ duy tr&igrave; v&agrave; tăng cường sức khỏe tinh thần v&agrave; thể chất</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 150%; margin: 0in 0in 24.0pt .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để cung cấp trải nghiệm cho kh&aacute;ch h&agrave;ng, ch&uacute;ng t&ocirc;i gi&uacute;p c&aacute;c đối t&aacute;c duy tr&igrave; v&agrave; cải thiện sức khỏe tinh thần v&agrave; thể chất của họ.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Hiểu mục đ&iacute;ch của sức khỏe v&agrave; an to&agrave;n</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 150%; margin: 0in 0in 24.0pt .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để cung cấp một m&ocirc;i trường an to&agrave;n v&agrave; bảo mật cho kh&aacute;ch h&agrave;ng của ch&uacute;ng t&ocirc;i, ch&uacute;ng t&ocirc;i sẽ tu&acirc;n thủ luật ph&aacute;p v&agrave; quy định, v&agrave; n&acirc;ng cao nhận thức nh&acirc;n vi&ecirc;n của ch&uacute;ng t&ocirc;i bằng c&aacute;ch tiến h&agrave;nh c&aacute;c hoạt động an to&agrave;n v&agrave; sức khỏe, gi&aacute;o dục.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Tạo m&ocirc;i trường lưu trữ an to&agrave;n v&agrave; bảo mật</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 150%; margin: 0in 0in 24.0pt .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i sẽ cố gắng ngăn chặn sự xuất hiện của tai nạn lao động để c&aacute;c cửa h&agrave;ng của ch&uacute;ng t&ocirc;i tiếp tục l&agrave; nơi l&agrave;m việc an to&agrave;n v&agrave; đảm bảo cho ch&uacute;ng t&ocirc;i v&agrave; những nơi đặc biệt cho kh&aacute;ch h&agrave;ng của ch&uacute;ng t&ocirc;i.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 150%;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif;">&nbsp;</span></p>`,
  `<p class="MsoNormal" style="text-align: center; line-height: 150%;" align="center"><strong><span style="font-size: 16.0pt; line-height: 150%; font-family: 'Inter',serif;">CH&Iacute;NH S&Aacute;CH BẢO MẬT TH&Ocirc;NG TIN</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">The Thanh Coffee nhận thức được tầm quan trọng của bảo mật th&ocirc;ng tin trong c&aacute;c hoạt động của qu&aacute;n, nhận ra mối đe dọa về tai nạn, tội phạm, sơ suất v&agrave; c&aacute;c mối đe dọa kh&aacute;c (sau đ&acirc;y gọi l&agrave; "sự cố bảo mật") nắm giữ t&agrave;i sản th&ocirc;ng tin. Ch&uacute;ng t&ocirc;i sẽ thiết lập v&agrave; tu&acirc;n thủ ch&iacute;nh s&aacute;ch n&agrave;y với mục đ&iacute;ch bảo vệ v&agrave; sử dụng n&oacute; một c&aacute;ch hợp l&yacute; v&agrave; an to&agrave;n.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Phạm vi &aacute;p dụng</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -30.0pt; line-height: 150%; mso-list: l0 level2 lfo1; tab-stops: list 1.0in; margin: 0in 0in .0001pt 1.0in;"><!-- [if !supportLists]--><span style="font-size: 10.0pt; mso-bidi-font-size: 13.0pt; line-height: 150%; font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">(1) Phạm vi &aacute;p dụng của ch&iacute;nh s&aacute;ch n&agrave;y sẽ l&agrave; tất cả c&aacute;c t&agrave;i sản th&ocirc;ng tin của The Thanh Coffee v&agrave; c&aacute;c nguồn lực li&ecirc;n quan đến con người, vật l&yacute; v&agrave; m&ocirc;i trường, bất kể ch&uacute;ng l&agrave; hữu h&igrave;nh hay v&ocirc; h&igrave;nh.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -30.0pt; line-height: 150%; mso-list: l0 level2 lfo1; tab-stops: list 1.0in; margin: 0in 0in .0001pt 1.0in;"><!-- [if !supportLists]--><span style="font-size: 10.0pt; mso-bidi-font-size: 13.0pt; line-height: 150%; font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">(2) Ch&iacute;nh s&aacute;ch n&agrave;y &aacute;p dụng cho tất cả những người sử dụng t&agrave;i sản th&ocirc;ng tin của qu&aacute;n, bao gồm cả nh&acirc;n vi&ecirc;n, v.v.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -30.0pt; line-height: 150%; mso-list: l0 level2 lfo1; tab-stops: list 1.0in; margin: 0in 0in .0001pt 1.0in;"><!-- [if !supportLists]--><span style="font-size: 10.0pt; mso-bidi-font-size: 13.0pt; line-height: 150%; font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">(3) Trong trường hợp hoạt động kinh doanh của qu&aacute;n trong phạm vi &aacute;p dụng ch&iacute;nh s&aacute;ch n&agrave;y được thu&ecirc; ngo&agrave;i cho b&ecirc;n thứ ba, n&oacute; sẽ chỉ được ủy th&aacute;c tr&ecirc;n cơ sở hợp đồng l&agrave;m r&otilde; c&aacute;c biện ph&aacute;p phải tu&acirc;n thủ v&agrave; tr&aacute;ch nhiệm trong trường hợp xảy ra sự cố bảo mật.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Thiết lập hệ thống an to&agrave;n th&ocirc;ng tin v&agrave; quy định nội bộ</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -30.0pt; line-height: 150%; mso-list: l0 level2 lfo1; tab-stops: list 1.0in; margin: 0in 0in .0001pt 1.0in;"><!-- [if !supportLists]--><span style="font-size: 10.0pt; mso-bidi-font-size: 13.0pt; line-height: 150%; font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">(1) The Thanh Coffee sẽ thiết lập một hệ thống bảo mật th&ocirc;ng tin th&iacute;ch hợp, l&agrave;m việc để duy tr&igrave; v&agrave; cải thiện bảo mật th&ocirc;ng tin, v&agrave; thiết lập một hệ thống để ngăn ngừa, ứng ph&oacute; v&agrave; phục hồi từ c&aacute;c sự cố bảo mật.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -30.0pt; line-height: 150%; mso-list: l0 level2 lfo1; tab-stops: list 1.0in; margin: 0in 0in .0001pt 1.0in;"><!-- [if !supportLists]--><span style="font-size: 10.0pt; mso-bidi-font-size: 13.0pt; line-height: 150%; font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">(2) The Thanh Coffee sẽ thiết lập c&aacute;c quy định nội bộ dựa tr&ecirc;n ch&iacute;nh s&aacute;ch n&agrave;y v&agrave; những người c&oacute; li&ecirc;n quan sẽ xử l&yacute; t&agrave;i sản th&ocirc;ng tin một c&aacute;ch th&iacute;ch hợp theo ch&uacute;ng.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Bảo vệ t&agrave;i sản th&ocirc;ng tin v&agrave; ứng ph&oacute; tai nạn</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -30.0pt; line-height: 150%; mso-list: l0 level2 lfo1; tab-stops: list 1.0in; margin: 0in 0in .0001pt 1.0in;"><!-- [if !supportLists]--><span style="font-size: 10.0pt; mso-bidi-font-size: 13.0pt; line-height: 150%; font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">(1) The Thanh Coffee nhận ra v&agrave; nắm bắt tầm quan trọng của tất cả c&aacute;c t&agrave;i sản th&ocirc;ng tin m&agrave; m&igrave;nh sở hữu từ c&aacute;c quan điểm về t&iacute;nh bảo mật, t&iacute;nh to&agrave;n vẹn v&agrave; t&iacute;nh khả dụng, đồng thời bảo vệ ch&uacute;ng một c&aacute;ch th&iacute;ch hợp.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -30.0pt; line-height: 150%; mso-list: l0 level2 lfo1; tab-stops: list 1.0in; margin: 0in 0in .0001pt 1.0in;"><!-- [if !supportLists]--><span style="font-size: 10.0pt; mso-bidi-font-size: 13.0pt; line-height: 150%; font-family: 'Courier New'; mso-fareast-font-family: 'Courier New'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">o<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">(2) Trong trường hợp The Thanh Coffee nhận thức được sự xuất hiện hoặc rủi ro của sự cố bảo mật, The Thanh Coffee sẽ kịp thời ứng ph&oacute; với sự xuất hiện v&agrave; l&acirc;y lan thiệt hại v&agrave; cố gắng khắc phục.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Thực hiện gi&aacute;o dục an to&agrave;n th&ocirc;ng tin</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 150%; margin: 0in 0in 24.0pt .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i sẽ tiếp tục tiến h&agrave;nh c&aacute;c hoạt động gi&aacute;o dục cho nh&acirc;n vi&ecirc;n của m&igrave;nh v&agrave; những người kh&aacute;c nhằm mục đ&iacute;ch phổ biến v&agrave; n&acirc;ng cao kiến thức về bảo mật th&ocirc;ng tin.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">5.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Tu&acirc;n thủ Luật ph&aacute;p v&agrave; Quy định</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 150%; margin: 0in 0in 24.0pt .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i sẽ tu&acirc;n thủ luật ph&aacute;p v&agrave; c&aacute;c quy định li&ecirc;n quan đến bảo mật th&ocirc;ng tin v&agrave; c&aacute;c ti&ecirc;u chuẩn kh&aacute;c.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">6.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Đ&aacute;nh gi&aacute; v&agrave; cải tiến</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 150%; margin: 0in 0in 24.0pt .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để đ&aacute;p ứng với những thay đổi trong m&ocirc;i trường, chẳng hạn như điều kiện x&atilde; hội v&agrave; tiến bộ c&ocirc;ng nghệ li&ecirc;n quan đến bảo mật th&ocirc;ng tin, ch&uacute;ng t&ocirc;i sẽ thường xuy&ecirc;n xem x&eacute;t v&agrave; cải thiện ch&iacute;nh s&aacute;ch n&agrave;y, cũng như hệ thống v&agrave; c&aacute;c quy định nội bộ dựa tr&ecirc;n n&oacute;.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif;">&nbsp;</span></p>`,
  `<p class="MsoNormal" style="text-align: center; line-height: 150%;" align="center"><strong><span style="font-size: 16.0pt; line-height: 150%; font-family: 'Inter',serif;">CH&Iacute;NH S&Aacute;CH BẢO MẬT</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&iacute;nh s&aacute;ch An to&agrave;n v&agrave; Bảo mật n&agrave;y ("Tuy&ecirc;n bố") &aacute;p dụng cho The Thanh Coffee, trang web do The Thanh Coffee sở hữu v&agrave; điều h&agrave;nh hướng kh&aacute;ch truy cập người d&ugrave;ng đến tuy&ecirc;n bố n&agrave;y. Ch&iacute;nh s&aacute;ch An to&agrave;n v&agrave; Bảo mật n&agrave;y kh&ocirc;ng &aacute;p dụng cho c&aacute;c trang web hoặc dịch vụ do b&ecirc;n thứ ba sở hữu v&agrave; điều h&agrave;nh.</span></p>
<p class="MsoNormal" style="margin-bottom: 7.5pt; line-height: 150%; mso-outline-level: 3;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">1. Th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi bạn sử dụng Dịch vụ của ch&uacute;ng t&ocirc;i, ch&uacute;ng t&ocirc;i thu thập một số th&ocirc;ng tin nhất định về bạn v&agrave; Dịch vụ bạn sử dụng. Th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập được chia th&agrave;nh ba loại ri&ecirc;ng biệt. (1) Th&ocirc;ng tin bạn cung cấp cho ch&uacute;ng t&ocirc;i, (2) Th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập tự động từ bạn khi bạn sử dụng Dịch vụ của ch&uacute;ng t&ocirc;i, (3) Th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập từ c&aacute;c nguồn kh&aacute;c</span></p>
<p class="MsoNormal" style="margin-bottom: 3.75pt; line-height: 150%; mso-outline-level: 4;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Th&ocirc;ng tin bạn cung cấp cho ch&uacute;ng t&ocirc;i</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi bạn sử dụng Dịch vụ của ch&uacute;ng t&ocirc;i, ch&uacute;ng t&ocirc;i thu thập th&ocirc;ng tin m&agrave; bạn cung cấp cho ch&uacute;ng t&ocirc;i. V&iacute; dụ về việc sử dụng Dịch vụ của ch&uacute;ng t&ocirc;i bao gồm mua h&agrave;ng tại một trong c&aacute;c cửa h&agrave;ng của ch&uacute;ng t&ocirc;i, duyệt một trong c&aacute;c trang web của ch&uacute;ng t&ocirc;i, tạo t&agrave;i khoản The Thanh Coffee, mua phiếu qu&agrave; tặng hoặc tham gia khảo s&aacute;t hoặc khuyến m&atilde;i. Bạn cũng c&oacute; thể cung cấp cho ch&uacute;ng t&ocirc;i th&ocirc;ng tin li&ecirc;n quan đến việc đăng k&yacute; v&agrave; hoạt động của c&aacute;c cửa h&agrave;ng The Thanh Coff&ecirc; được nhượng quyền. Th&ocirc;ng tin bạn cung cấp cho ch&uacute;ng t&ocirc;i c&oacute; thể bao gồm t&ecirc;n, họ, t&ecirc;n người d&ugrave;ng, mật khẩu, địa chỉ email, m&atilde; zip, số điện thoại, th&ocirc;ng tin t&agrave;i khoản t&agrave;i ch&iacute;nh như số thẻ t&iacute;n dụng, ng&agrave;y sinh, nơi sinh, th&ocirc;ng tin nh&acirc;n khẩu học v&agrave; bất kỳ th&ocirc;ng tin n&agrave;o kh&aacute;c m&agrave; bạn chọn cung cấp cho ch&uacute;ng t&ocirc;i.</span></p>
<p class="MsoNormal" style="margin-bottom: 3.75pt; line-height: 150%; mso-outline-level: 4;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập khi bạn sử dụng dịch vụ của ch&uacute;ng t&ocirc;i</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi bạn sử dụng dịch vụ của ch&uacute;ng t&ocirc;i, ch&uacute;ng t&ocirc;i c&oacute; thể thu thập th&ocirc;ng tin về c&aacute;c dịch vụ bạn sử dụng v&agrave; c&aacute;ch bạn sử dụng ch&uacute;ng. Th&ocirc;ng tin n&agrave;y bao gồm:<br>Th&ocirc;ng tin mua h&agrave;ng - Ch&uacute;ng t&ocirc;i c&oacute; thể thu thập th&ocirc;ng tin về c&aacute;c sản phẩm bạn mua, bao gồm th&ocirc;ng tin về nơi bạn mua sản phẩm, tần suất bạn mua ch&uacute;ng v&agrave; lợi nhuận bạn kiếm được từ việc mua h&agrave;ng của m&igrave;nh.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Th&ocirc;ng tin về việc bạn sử dụng thiết bị v&agrave; trang web của bạn khi bạn c&agrave;i đặt ứng dụng di động của ch&uacute;ng t&ocirc;i hoặc sử dụng m&aacute;y t&iacute;nh, m&aacute;y t&iacute;nh bảng, điện thoại th&ocirc;ng minh hoặc thiết bị kh&aacute;c để truy cập c&aacute;c dịch vụ của ch&uacute;ng t&ocirc;i th&ocirc;ng qua trang web, sản phẩm để b&aacute;n hoặc t&agrave;i sản trực tuyến của ch&uacute;ng t&ocirc;i; Ch&uacute;ng t&ocirc;i c&oacute; thể thu thập th&ocirc;ng tin về thiết bị v&agrave; trang web của bạn.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Th&ocirc;ng tin vị tr&iacute; - khi bạn sử dụng điện thoại th&ocirc;ng minh hoặc thiết bị di động kh&aacute;c để truy cập Dịch vụ của ch&uacute;ng t&ocirc;i, khi bạn sử dụng m&aacute;y t&iacute;nh để truy cập trang web của ch&uacute;ng t&ocirc;i hoặc khi bạn sử dụng dịch vụ định vị cửa h&agrave;ng của ch&uacute;ng t&ocirc;i trong ứng dụng di động của ch&uacute;ng t&ocirc;i hoặc tr&ecirc;n phi&ecirc;n bản web của Đặt h&agrave;ng &amp;; Thanh to&aacute;n tr&ecirc;n thiết bị di động; Ch&uacute;ng t&ocirc;i c&oacute; thể thu thập th&ocirc;ng tin vị tr&iacute; thực tế của bạn.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i c&oacute; thể kết hợp th&ocirc;ng tin n&agrave;y với c&aacute;c địa điểm kh&aacute;c (dựa tr&ecirc;n địa chỉ IP của bạn v&agrave; th&ocirc;ng tin như th&ocirc;ng tin thanh to&aacute;n hoặc m&atilde; zip) để cung cấp cho bạn th&ocirc;ng tin về c&aacute;c cửa h&agrave;ng gần bạn hoặc để cung cấp cho bạn c&aacute;c dịch vụ kh&aacute;c tr&ecirc;n thiết bị di động của bạn. Ch&uacute;ng t&ocirc;i chỉ chia sẻ th&ocirc;ng tin vị tr&iacute; của bạn với c&aacute;c c&ocirc;ng ty gi&uacute;p ch&uacute;ng t&ocirc;i cung cấp dịch vụ cho bạn v&agrave; gi&uacute;p ch&uacute;ng t&ocirc;i hiểu c&aacute;ch dịch vụ của ch&uacute;ng t&ocirc;i được sử dụng. Nếu bạn muốn chọn kh&ocirc;ng tham gia bộ sưu tập th&ocirc;ng tin vị tr&iacute; n&agrave;y, vui l&ograve;ng xem phần c&oacute; ti&ecirc;u đề "Lựa chọn của bạn" b&ecirc;n dưới.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Th&ocirc;ng tin camera tại cửa h&agrave;ng - Ch&uacute;ng t&ocirc;i sử dụng camera tại cửa h&agrave;ng để t&igrave;m c&aacute;ch giữ an to&agrave;n cho nh&acirc;n vi&ecirc;n v&agrave; bạn v&agrave; cải thiện trải nghiệm kh&aacute;ch h&agrave;ng tại c&aacute;c cửa h&agrave;ng của ch&uacute;ng t&ocirc;i. Ch&uacute;ng t&ocirc;i kh&ocirc;ng sử dụng c&aacute;c camera n&agrave;y để nhận dạng c&aacute; nh&acirc;n, trừ khi cần thiết cho mục đ&iacute;ch an ninh.</span></p>
<p class="MsoNormal" style="margin-bottom: 3.75pt; line-height: 150%; mso-outline-level: 4;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập khi bạn sử dụng dịch vụ của ch&uacute;ng t&ocirc;i</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i cũng thu thập th&ocirc;ng tin c&oacute; sẵn c&ocirc;ng khai. V&iacute; dụ: ch&uacute;ng t&ocirc;i c&oacute; thể thu thập th&ocirc;ng tin m&agrave; bạn đăng tr&ecirc;n blog, ph&ograve;ng tr&ograve; chuyện, Facebook v&agrave; c&aacute;c mạng x&atilde; hội như X. Ch&uacute;ng t&ocirc;i cũng c&oacute; thể thu thập th&ocirc;ng tin về bạn từ c&aacute;c c&ocirc;ng ty v&agrave; tổ chức kh&aacute;c. Bằng c&aacute;ch t&iacute;ch lũy th&ocirc;ng tin bổ sung về bạn, ch&uacute;ng t&ocirc;i c&oacute; thể sửa chữa bất kỳ sự kh&ocirc;ng ch&iacute;nh x&aacute;c n&agrave;o v&agrave; cung cấp cho bạn c&aacute;c ưu đ&atilde;i sản phẩm v&agrave; ưu đ&atilde;i đặc biệt m&agrave; ch&uacute;ng t&ocirc;i nghĩ rằng bạn c&oacute; thể quan t&acirc;m hơn.</span></p>
<p class="MsoNormal" style="margin-bottom: 7.5pt; line-height: 150%; mso-outline-level: 3;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">2. Ch&uacute;ng t&ocirc;i sử dụng th&ocirc;ng tin thu thập được như thế n&agrave;o?</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i c&oacute; thể sử dụng th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập về bạn theo nhiều c&aacute;ch kh&aacute;c nhau, bao gồm theo những c&aacute;ch sau:</span></p>
<ul style="margin-top: 0in;" type="disc">
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để xử l&yacute; việc mua h&agrave;ng h&oacute;a v&agrave; dịch vụ của bạn</span></li>
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để xử l&yacute; việc mua h&agrave;ng h&oacute;a v&agrave; dịch vụ của bạn</span></li>
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để trả lời c&aacute;c c&acirc;u hỏi v&agrave; y&ecirc;u cầu dịch vụ kh&aacute;ch h&agrave;ng của bạn;</span></li>
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để đăng nhận x&eacute;t v&agrave; &yacute; kiến của bạn tr&ecirc;n trang web của ch&uacute;ng t&ocirc;i</span></li>
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để gửi cho bạn c&aacute;c chương tr&igrave;nh khuyến m&atilde;i c&aacute; nh&acirc;n v&agrave; ưu đ&atilde;i đặc biệt;</span></li>
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để th&ocirc;ng b&aacute;o cho bạn về c&aacute;c thương hiệu, sản phẩm, sự kiện v&agrave; c&aacute;c chương tr&igrave;nh khuyến m&atilde;i kh&aacute;c của ch&uacute;ng t&ocirc;i;</span></li>
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để duy tr&igrave; v&agrave; cải thiện trang web, sản phẩm v&agrave; dịch vụ ch&uacute;ng t&ocirc;i cung cấp</span></li>
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để ph&aacute;t hiện, ngăn chặn hoặc điều tra c&aacute;c vi phạm an ninh hoặc c&aacute;c hoạt động bất hợp ph&aacute;p;</span></li>
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để duy tr&igrave; hồ sơ th&iacute;ch hợp cho c&aacute;c mục đ&iacute;ch h&agrave;nh ch&iacute;nh nội bộ</span></li>
<li class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Để đ&aacute;nh gi&aacute; c&aacute;c cơ hội nhượng quyền thương mại v&agrave; li&ecirc;n lạc với bạn</span></li>
</ul>
<p class="MsoNormal" style="margin-bottom: 7.5pt; line-height: 150%; mso-outline-level: 3;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">3. L&agrave;m thế n&agrave;o để ch&uacute;ng t&ocirc;i chia sẻ th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập?</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i c&oacute; thể chia sẻ th&ocirc;ng tin của bạn trong c&aacute;c trường hợp sau:</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi ch&uacute;ng t&ocirc;i l&agrave;m việc c&ugrave;ng nhau - để quản l&yacute;, ph&acirc;n t&iacute;ch v&agrave; ra quyết định ph&ugrave; hợp, bao gồm đưa ra quyết định li&ecirc;n quan đến nhượng quyền thương mại của ch&uacute;ng t&ocirc;i, mở rộng v&agrave; quảng b&aacute; c&aacute;c sản phẩm v&agrave; dịch vụ m&agrave; ch&uacute;ng t&ocirc;i cung cấp, v&agrave; thực hiện c&aacute;c đơn đặt h&agrave;ng v&agrave; y&ecirc;u cầu của kh&aacute;ch h&agrave;ng, v&agrave; cho c&aacute;c mục đ&iacute;ch kh&aacute;c như được m&ocirc; tả trong Tuy&ecirc;n bố n&agrave;y; Ch&uacute;ng t&ocirc;i c&oacute; thể chia sẻ th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập với c&aacute;c chi nh&aacute;nh của ch&uacute;ng t&ocirc;i để họ sử dụng.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi ch&uacute;ng t&ocirc;i l&agrave;m việc với c&aacute;c nh&agrave; cung cấp dịch vụ - ch&uacute;ng t&ocirc;i c&oacute; thể chia sẻ th&ocirc;ng tin của bạn với c&aacute;c nh&agrave; cung cấp dịch vụ cung cấp cho ch&uacute;ng t&ocirc;i c&aacute;c dịch vụ hỗ trợ như xử l&yacute; thẻ t&iacute;n dụng, bảo tr&igrave; trang web, gửi email, lập bản đồ vị tr&iacute;, xử l&yacute; v&agrave; chuyển ph&aacute;t bưu điện v&agrave; dịch vụ ph&acirc;n t&iacute;ch. Ch&uacute;ng t&ocirc;i y&ecirc;u cầu c&aacute;c c&ocirc;ng ty n&agrave;y kh&ocirc;ng thu thập, sử dụng hoặc tiết lộ th&ocirc;ng tin của bạn trừ khi họ đang thực hiện c&ocirc;ng việc thay mặt ch&uacute;ng t&ocirc;i hoặc được y&ecirc;u cầu tiết lộ th&ocirc;ng tin của bạn theo luật.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi thực hiện chuyển nhượng kinh doanh - nếu bạn tham gia v&agrave;o một t&igrave;nh huống kh&aacute;c li&ecirc;n quan đến việc s&aacute;p nhập hoặc chuyển nhượng to&agrave;n bộ hoặc một phần t&agrave;i sản kinh doanh của bạn, ch&uacute;ng t&ocirc;i c&oacute; thể chia sẻ th&ocirc;ng tin của bạn với doanh nghiệp hoặc c&aacute; nh&acirc;n li&ecirc;n quan đến việc đ&agrave;m ph&aacute;n hoặc chuyển nhượng.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i c&oacute; thể tiết lộ th&ocirc;ng tin của bạn nếu ch&uacute;ng t&ocirc;i tin rằng việc tiết lộ l&agrave; bắt buộc theo luật, rằng việc tiết lộ l&agrave; cần thiết để thực thi c&aacute;c thỏa thuận hoặc ch&iacute;nh s&aacute;ch của ch&uacute;ng t&ocirc;i hoặc việc tiết lộ sẽ gi&uacute;p bảo vệ quyền, t&agrave;i sản hoặc sự an to&agrave;n của The Thanh Coffee, bạn hoặc c&aacute;c đối t&aacute;c của ch&uacute;ng t&ocirc;i.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi ch&uacute;ng t&ocirc;i chia sẻ th&ocirc;ng tin của bạn với c&aacute;c c&ocirc;ng ty kh&aacute;c cho mục đ&iacute;ch tiếp thị - ch&uacute;ng t&ocirc;i c&oacute; thể chia sẻ th&ocirc;ng tin của bạn với c&aacute;c nh&agrave; cung cấp dịch vụ sử dụng th&ocirc;ng tin của bạn để cung cấp cho bạn c&aacute;c chương tr&igrave;nh khuyến m&atilde;i v&agrave; ưu đ&atilde;i đặc biệt. Ch&uacute;ng t&ocirc;i cũng c&oacute; thể chia sẻ số liệu thống k&ecirc; tổng hợp ẩn danh về việc bạn sử dụng c&aacute;c trang web v&agrave; dịch vụ của ch&uacute;ng t&ocirc;i với c&aacute;c c&ocirc;ng ty kh&aacute;c.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi bạn đồng &yacute; - nếu bạn cho ph&eacute;p ch&uacute;ng t&ocirc;i hoặc hướng dẫn chia sẻ th&ocirc;ng tin về bạn, ch&uacute;ng t&ocirc;i c&oacute; thể chia sẻ th&ocirc;ng tin đ&oacute; với c&aacute;c c&ocirc;ng ty kh&aacute;c.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi th&ocirc;ng tin kh&ocirc;ng nhận dạng bạn - Ch&uacute;ng t&ocirc;i c&oacute; thể chia sẻ th&ocirc;ng tin của bạn theo c&aacute;ch kh&ocirc;ng trực tiếp nhận dạng bạn. V&iacute; dụ: ch&uacute;ng t&ocirc;i c&oacute; thể kết hợp th&ocirc;ng tin về bạn với th&ocirc;ng tin về c&aacute;c c&aacute; nh&acirc;n kh&aacute;c v&agrave; chia sẻ th&ocirc;ng tin kết hợp đ&oacute; theo c&aacute;ch kh&ocirc;ng li&ecirc;n kết th&ocirc;ng tin của bạn với bạn.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Khi bạn đăng tr&ecirc;n trang web của ch&uacute;ng t&ocirc;i - Nếu bạn đăng th&ocirc;ng tin tr&ecirc;n blog hoặc một phần kh&aacute;c của trang web của ch&uacute;ng t&ocirc;i, th&ocirc;ng tin bạn đăng v&agrave; th&ocirc;ng tin bạn đăng, bao gồm t&ecirc;n người d&ugrave;ng của bạn, c&oacute; thể hiển thị cho những kh&aacute;ch truy cập kh&aacute;c tr&ecirc;n trang web của ch&uacute;ng t&ocirc;i.</span></p>
<p class="MsoNormal" style="margin-bottom: 7.5pt; line-height: 150%; mso-outline-level: 3;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">3. Lựa chọn của bạn</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Lựa chọn li&ecirc;n quan đến th&ocirc;ng tin khuyến mại</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Bạn c&oacute; thể cung cấp cho ch&uacute;ng t&ocirc;i t&ugrave;y chọn của bạn khi bạn đăng nhập v&agrave;o t&agrave;i khoản The Thanh Coffee, sửa t&ugrave;y chọn khuyến m&atilde;i trực tuyến trong m&agrave;n h&igrave;nh quản l&yacute; hồ sơ t&agrave;i khoản của bạn hoặc điều chỉnh c&agrave;i đặt văn bản v&agrave; th&ocirc;ng b&aacute;o trong c&agrave;i đặt thiết bị di động của bạn hoặc l&agrave;m theo hướng dẫn chọn kh&ocirc;ng tham gia trong email quảng c&aacute;o m&agrave; ch&uacute;ng t&ocirc;i gửi cho bạn. Bạn c&oacute; thể chọn kh&ocirc;ng nhận email quảng c&aacute;o, tin nhắn văn bản, cuộc gọi điện thoại v&agrave; thư bưu ch&iacute;nh.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ngo&agrave;i ra, bạn c&oacute; thể cho ch&uacute;ng t&ocirc;i biết rằng bạn kh&ocirc;ng muốn nhận một số hoặc tất cả c&aacute;c th&ocirc;ng tin quảng c&aacute;o n&agrave;y bằng c&aacute;ch gọi cho ch&uacute;ng t&ocirc;i theo th&ocirc;ng tin li&ecirc;n hệ b&ecirc;n dưới.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span lang="ZH-CN" style="font-size: 13.0pt; line-height: 150%; font-family: 'Microsoft YaHei',sans-serif; mso-ascii-font-family: 'Inter'; mso-hansi-font-family: 'Inter'; mso-bidi-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">【</span><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Li&ecirc;n hệ Hotline</span><span lang="ZH-CN" style="font-size: 13.0pt; line-height: 150%; font-family: 'Microsoft YaHei',sans-serif; mso-ascii-font-family: 'Inter'; mso-hansi-font-family: 'Inter'; mso-bidi-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">】</span><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><br>Giờ l&agrave;m việc: 09: 00 ~ 22: 00 (gồm thứ bảy, chủ nhật, ng&agrave;y lễ quốc gia, v&agrave; cuối năm v&agrave; ng&agrave;y lễ năm mới)</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Xin lưu &yacute; rằng ngay cả khi bạn chọn kh&ocirc;ng nhận th&ocirc;ng tin quảng c&aacute;o từ ch&uacute;ng t&ocirc;i, ch&uacute;ng t&ocirc;i vẫn c&oacute; thể gửi cho bạn th&ocirc;ng tin phi quảng c&aacute;o, bao gồm email về t&agrave;i khoản, giao dịch mua hoặc ứng dụng nhượng quyền thương mại của bạn.</span></p>
<p class="MsoNormal" style="margin-bottom: 3.75pt; line-height: 150%; mso-outline-level: 4;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">C&aacute;c lựa chọn bạn thực hiện li&ecirc;n quan đến việc thu thập th&ocirc;ng tin</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Bạn cũng c&oacute; thể chọn th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập về bạn.</span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Th&ocirc;ng tin vị tr&iacute; - Ch&uacute;ng t&ocirc;i chỉ c&oacute; thể thu thập th&ocirc;ng tin vị tr&iacute; thực tế của bạn khi bạn sử dụng điện thoại th&ocirc;ng minh hoặc thiết bị di động kh&aacute;c để truy cập Dịch vụ của ch&uacute;ng t&ocirc;i, khi dịch vụ định vị cho c&aacute;c ứng dụng di động, tr&ecirc;n phi&ecirc;n bản web của Đặt h&agrave;ng &amp;; Thanh to&aacute;n tr&ecirc;n thiết bị di động c&oacute; sẵn hoặc khi thẩm quyền của thiết bị di động của bạn cho ph&eacute;p th&ocirc;ng tin n&agrave;y được truyền đạt. Nếu bạn kh&ocirc;ng muốn ch&uacute;ng t&ocirc;i thu thập th&ocirc;ng tin vị tr&iacute;, bạn c&oacute; thể chọn </span></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">C&ocirc;ng nghệ Kh&ocirc;ng theo d&otilde;i &ndash; Một số tr&igrave;nh duyệt web hiện đại c&oacute; c&agrave;i đặt Kh&ocirc;ng theo d&otilde;i gửi Kh&ocirc;ng theo d&otilde;i trong ti&ecirc;u đề của c&aacute;c trang web bạn truy cập với th&ocirc;ng tin cho biết rằng bạn kh&ocirc;ng muốn h&agrave;nh vi của m&igrave;nh bị theo d&otilde;i. Ch&uacute;ng t&ocirc;i hiện kh&ocirc;ng hỗ trợ c&aacute;c tr&igrave;nh duyệt gửi t&iacute;n hiệu Kh&ocirc;ng Theo d&otilde;i.</span></p>
<p class="MsoNormal" style="margin-bottom: 7.5pt; line-height: 150%; mso-outline-level: 3;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">4. Ch&uacute;ng t&ocirc;i bảo vệ th&ocirc;ng tin của bạn như thế n&agrave;o?</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">The Thanh Coffee bảo vệ th&ocirc;ng tin của bạn bằng c&aacute;ch sử dụng c&aacute;c ti&ecirc;u chuẩn bảo mật kỹ thuật, vật l&yacute; v&agrave; h&agrave;nh ch&iacute;nh để giảm nguy cơ mất m&aacute;t, lạm dụng, truy cập tr&aacute;i ph&eacute;p, tiết lộ hoặc thay đổi th&ocirc;ng tin của bạn theo Đạo luật Quyền ri&ecirc;ng tư. Một số biện ph&aacute;p bảo vệ của ch&uacute;ng t&ocirc;i bao gồm tường lửa, m&atilde; h&oacute;a dữ liệu, kiểm so&aacute;t truy cập vật l&yacute; v&agrave; kiểm so&aacute;t th&ocirc;ng tin quản trị. Khi bạn gửi th&ocirc;ng tin nhạy cảm cao (v&iacute; dụ: số thẻ t&iacute;n dụng) th&ocirc;ng qua trang web của ch&uacute;ng t&ocirc;i hoặc trong một trong c&aacute;c ứng dụng di động của ch&uacute;ng t&ocirc;i, ch&uacute;ng t&ocirc;i sẽ m&atilde; h&oacute;a n&oacute;. Mặc d&ugrave; ch&uacute;ng t&ocirc;i sử dụng c&aacute;c c&ocirc;ng nghệ v&agrave; quy tr&igrave;nh bảo mật để gi&uacute;p bảo vệ th&ocirc;ng tin c&aacute; nh&acirc;n của bạn, nhưng kh&ocirc;ng c&oacute; hệ thống hoặc mạng n&agrave;o c&oacute; thể đảm bảo bảo mật 100%.</span></p>
<p class="MsoNormal" style="margin-bottom: 7.5pt; line-height: 150%; mso-outline-level: 3;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">5. Sửa đổi Tuy&ecirc;n bố n&agrave;y</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Tuy&ecirc;n bố n&agrave;y được ban h&agrave;nh v&agrave;o ng&agrave;y được chỉ định ở đầu trang web n&agrave;y. Ch&uacute;ng t&ocirc;i c&oacute; thể sửa đổi tuy&ecirc;n bố n&agrave;y theo thời gian. Nếu ch&uacute;ng t&ocirc;i thực hiện c&aacute;c thay đổi quan trọng, ch&uacute;ng t&ocirc;i sẽ xuất bản một tuy&ecirc;n bố sửa đổi tr&ecirc;n trang n&agrave;y v&agrave; thay đổi ng&agrave;y ở đầu trang web n&agrave;y. Ch&uacute;ng t&ocirc;i khuyến kh&iacute;ch bạn kiểm tra ng&agrave;y n&agrave;y mỗi khi bạn truy cập trang web n&agrave;y để kiểm tra bất kỳ sửa đổi v&agrave; thay đổi n&agrave;o đối với tuy&ecirc;n bố n&agrave;y. Ch&uacute;ng t&ocirc;i sẽ th&ocirc;ng b&aacute;o cho bạn tr&ecirc;n trang web n&agrave;y về bất kỳ thay đổi n&agrave;o đối với Tuy&ecirc;n bố n&agrave;y c&oacute; thể ảnh hưởng nghi&ecirc;m trọng đến c&aacute;ch ch&uacute;ng t&ocirc;i sử dụng hoặc tiết lộ th&ocirc;ng tin c&aacute; nh&acirc;n của bạn, trước ng&agrave;y thay đổi c&oacute; hiệu lực.</span></p>
<p class="MsoNormal" style="margin-bottom: 7.5pt; line-height: 150%; mso-outline-level: 3;"><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">6. Th&ocirc;ng tin li&ecirc;n lạc</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i hoan ngh&ecirc;nh c&aacute;c c&acirc;u hỏi, nhận x&eacute;t v&agrave; mối quan t&acirc;m của bạn về quyền ri&ecirc;ng tư. Bạn c&oacute; thể li&ecirc;n hệ với ch&uacute;ng t&ocirc;i bằng c&aacute;ch sử dụng th&ocirc;ng tin li&ecirc;n hệ b&ecirc;n dưới.</span></p>
<p class="MsoNormal" style="margin-bottom: .0001pt; line-height: 150%;"><span lang="ZH-CN" style="font-size: 13.0pt; line-height: 150%; font-family: 'Microsoft YaHei',sans-serif; mso-ascii-font-family: 'Inter'; mso-hansi-font-family: 'Inter'; mso-bidi-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">【</span><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">C&aacute;c c&acirc;u hỏi li&ecirc;n quan đến dữ liệu c&aacute; nh&acirc;n được lưu giữ</span><span lang="ZH-CN" style="font-size: 13.0pt; line-height: 150%; font-family: 'Microsoft YaHei',sans-serif; mso-ascii-font-family: 'Inter'; mso-hansi-font-family: 'Inter'; mso-bidi-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">】</span><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><br>Hotline:<br>(Giờ l&agrave;m việc: 09: 00 ~ 22: 00, bao gồm cả thứ bảy, chủ nhật, ng&agrave;y lễ quốc gia, v&agrave; cuối năm v&agrave; ng&agrave;y lễ năm mới)</span></p>
<p class="MsoNormal" style="line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif;">&nbsp;</span></p>`,
  `<p class="MsoNormal" style="text-align: center; line-height: 150%;" align="center"><strong><span style="font-size: 16.0pt; line-height: 150%; font-family: 'Inter',serif;">CH&Iacute;NH S&Aacute;CH C&Aacute;C B&Ecirc;N LI&Ecirc;N QUAN</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 24.0pt; line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Dựa tr&ecirc;n tầm quan trọng của việc đồng tạo ra gi&aacute; trị kh&ocirc;ng chỉ với c&aacute;c cổ đ&ocirc;ng m&agrave; c&ograve;n với nh&acirc;n vi&ecirc;n, đối t&aacute;c kinh doanh, kh&aacute;ch h&agrave;ng, chủ nợ, cộng đồng địa phương v&agrave; c&aacute;c b&ecirc;n li&ecirc;n quan đa dạng kh&aacute;c trong quản l&yacute; doanh nghiệp, The Thanh Coffee sẽ hợp t&aacute;c ph&ugrave; hợp với nhiều b&ecirc;n li&ecirc;n quan. Tr&ecirc;n hết, ch&uacute;ng t&ocirc;i sẽ th&uacute;c đẩy c&aacute;c s&aacute;ng kiến sau, dựa tr&ecirc;n tầm quan trọng của việc trả lại cho nh&acirc;n vi&ecirc;n v&agrave; xem x&eacute;t c&aacute;c đối t&aacute;c kinh doanh, từ quan điểm ph&acirc;n phối hợp l&yacute; lợi nhuận v&agrave; kết quả được tạo ra th&ocirc;ng qua việc đồng s&aacute;ng tạo gi&aacute; trị v&agrave; cải thiện năng suất cho nhiều b&ecirc;n li&ecirc;n quan sẽ dẫn đến việc duy tr&igrave; đ&agrave; tăng lương v&agrave; ph&aacute;t triển kinh tế bền vững.</span></p>
<p class="MsoNormal" style="text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Trả lại cho nh&acirc;n vi&ecirc;n</span></strong></p>
<p class="MsoNormal" style="line-height: 150%; margin: 0in 0in 24.0pt .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i sẽ l&agrave;m việc để đạt được tăng trưởng bền vững v&agrave; cải thiện năng suất bằng c&aacute;ch cải thiện sự tham gia của nh&acirc;n vi&ecirc;n v&agrave; ph&aacute;t triển khả năng của nh&acirc;n vi&ecirc;n v&agrave; tập trung v&agrave;o việc tối đa h&oacute;a gi&aacute; trị gia tăng. Tr&ecirc;n hết, ch&uacute;ng t&ocirc;i sẽ sử dụng lợi nhuận tạo ra l&agrave;m nguồn vốn để đảm bảo ng&acirc;n s&aacute;ch tăng lương dựa tr&ecirc;n xu hướng thị trường v&agrave; tăng lương ph&ugrave; hợp. Ngo&agrave;i ra, ch&uacute;ng t&ocirc;i mong muốn mang lại lợi nhuận bền vững cho c&aacute;c đối t&aacute;c của m&igrave;nh bằng c&aacute;ch t&iacute;ch cực đầu tư v&agrave;o nguồn nh&acirc;n lực để g&oacute;p phần gắn kết hơn nữa v&agrave; cải thiện năng suất.<br><br>Cụ thể, ch&uacute;ng t&ocirc;i sẽ đảm bảo ng&acirc;n s&aacute;ch th&iacute;ch hợp cho việc tăng lương để đ&aacute;p ứng với sự ph&aacute;t triển gi&aacute; cả v&agrave; điều kiện kinh tế, đồng thời tiếp tục ph&aacute;t triển hệ thống bồi thường dựa tr&ecirc;n hiệu suất của ch&uacute;ng t&ocirc;i. Ngo&agrave;i ra, với mục đ&iacute;ch hiện thực h&oacute;a sự pha trộn giữa c&ocirc;ng việc v&agrave; cuộc sống, ch&uacute;ng t&ocirc;i đang nỗ lực thiết lập một phong c&aacute;ch l&agrave;m việc đ&aacute;p ứng cao cho giai đoạn cuộc sống của mỗi c&aacute; nh&acirc;n v&agrave; phong c&aacute;ch l&agrave;m việc độc đ&aacute;o của Starbucks nhằm tối đa h&oacute;a hiệu suất như một nh&oacute;m. Ngo&agrave;i ra, ch&uacute;ng t&ocirc;i sẽ tiếp tục cung cấp c&aacute;c cơ hội đ&agrave;o tạo v&agrave; quản l&yacute; hiệu suất cho c&aacute;c đối t&aacute;c của ch&uacute;ng t&ocirc;i để tiếp tục l&agrave;m việc với sự tham gia cao, bất kể loại việc l&agrave;m của nh&acirc;n vi&ecirc;n v&agrave; nh&acirc;n vi&ecirc;n b&aacute;n thời gian.</span></p>
<p class="MsoNormal" style="text-indent: -.25in; line-height: 150%; mso-outline-level: 4; mso-list: l0 level1 lfo1; tab-stops: list .5in; margin: 0in 0in 3.75pt .5in;"><!-- [if !supportLists]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Inter';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">C&acirc;n nhắc cho c&aacute;c đối t&aacute;c kinh doanh</span></strong></p>
<p class="MsoNormal" style="line-height: 150%; margin: 0in 0in 24.0pt .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i sẽ tiếp tục l&agrave;m việc để tu&acirc;n thủ c&aacute;c nội dung của Tuy&ecirc;n bố x&acirc;y dựng quan hệ đối t&aacute;c.</span></p>
<p class="MsoNormal" style="line-height: 150%; margin: 0in 0in 24.0pt .5in;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif; mso-fareast-font-family: 'Inter'; mso-font-kerning: 0pt; mso-ligatures: none;">Ch&uacute;ng t&ocirc;i sẽ x&aacute;c nhận t&igrave;nh trạng của c&aacute;c s&aacute;ng kiến n&agrave;y v&agrave; đạt được tiến bộ ổn định tr&ecirc;n c&aacute;c hạng mục n&agrave;y.</span></p>
<p class="MsoNormal" style="line-height: 150%;"><span style="font-size: 13.0pt; line-height: 150%; font-family: 'Inter',serif;">&nbsp;</span></p>`,
];

const PolicyContent = () => {
  const { id } = useParams();
  const content = policiesContent[id];
  return (
    <Box sx={{ ...styles.fontSize13 }}>
      <Logotop />
      <Navbardesktop />
      <Box
        sx={{
          p: "240px 239px 140px 239px",
          ...styles.fontSize13,
          "@media (max-width:900px)": { p: "20px" },
        }}
      >
        <Box
          sx={{
            pb: "64px",
            fontSize: "20px",
            "@media (max-width:900px)": {
              mt: "160px",
              fontSize: "32px",
              pb: "30px",
            },
          }}
          dangerouslySetInnerHTML={{ __html: content }}
        ></Box>
      </Box>
      <FooterDesktop />
    </Box>
  );
};

export default PolicyContent;
